language: c
sudo: required

before_install:
    - sudo apt-get clean && sudo apt-get update
    - sudo apt-get install gcc gfortran hdf5-tools libopenmpi-dev libhdf5-openmpi-dev 
    - which gfortran
    - which gcc
    - which h5dump

script:
    - pwd
    - cd ED/build/
    - ./install.sh -k C -p travisci -g
    - ls
